apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    grafana_datasources: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Mimir
        type: prometheus
        access: proxy
        url: http://mimir-gateway/prometheus
        uid: mimir
        isDefault: true
        jsonData:
          exemplarTraceIDDestinations:
            - name: trace_is
              datasourceUid: tempo

      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        uid: tempo
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            spanStartTimeShift: "-1h"
            spanEndTimeShift: "1h"
            filterByTraceID: true
            tags: []
          tracesToMetrics:
            datasourceUid: tempo
            tags:
              - key: service.name
                value: service_name

      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        uid: loki