mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317

  exporters:
    otlp_http/tempo:
      endpoint: http://tempo:4318
      tls:
        insecure: true
    otlp_http/loki:
      endpoint: http://loki:3100/otlp
      tls:
        insecure: true
    prometheusremotewrite/mimir:
      endpoint: http://mimir-gateway/api/v1/push
      tls:
        insecure: true

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp_http/tempo]
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [prometheusremotewrite/mimir]
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp_http/loki]

ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    protocol: TCP